all:
  children:
    deb:
      hosts:
        ubuntu_test:
          ansible_connection: docker
          ansible_user: root
          ansible_remote_tmp: /tmp
    el:
      hosts:
        centos_test:
          ansible_connection: docker
          ansible_user: root
          ansible_remote_tmp: /tmp
    local:
      hosts:
        localhost:
          ansible_connection: local